# Generated by Django 5.0.6 on 2024-05-18 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Tutorials', 'Tutorials'), ('News and Updates', 'News And Updates'), ('Tips and Tricks', 'Tips And Tricks'), ('Others', 'Others')], default='Tutorials', max_length=30)),
                ('author', models.CharField(max_length=100)),
                ('connection_platform', models.CharField(choices=[('Website', 'Website'), ('Email', 'Email'), ('Twitter(X)', 'Twitter X'), ('Instagram', 'Instagram'), ('Github', 'Github'), ('LinkedIn', 'Linkedin')], default='Email', max_length=12)),
                ('connect_author', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('cover_image', models.ImageField(blank=True, upload_to='blogpost-images')),
                ('date_posted', models.DateField(auto_now_add=True)),
                ('time_posted', models.TimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date_posted'],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=100)),
                ('edition', models.IntegerField(default=1)),
                ('isbn', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('number', models.IntegerField()),
                ('completion_status', models.CharField(choices=[('Pending', 'Pending'), ('Under Review', 'Under Review'), ('Completed', 'Completed')], default='Pending', max_length=15)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repo.book')),
            ],
        ),
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_type', models.CharField(choices=[('Review Question', 'Review Question'), ('Exercise', 'Exercise')], default='Exercise', max_length=20)),
                ('exercise_number', models.CharField(max_length=5)),
                ('answer', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='solution-images')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repo.chapter')),
            ],
        ),
    ]
