# Generated by Django 5.0.6 on 2024-05-21 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0002_customuser_is_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='cover_image',
        ),
        migrations.RemoveField(
            model_name='solution',
            name='image',
        ),
        migrations.CreateModel(
            name='BlogPostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='None')),
                ('blogpost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repo.blogpost')),
            ],
        ),
        migrations.CreateModel(
            name='SolutionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='None')),
                ('solution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repo.solution')),
            ],
        ),
    ]
