# Generated by Django 5.0.6 on 2024-06-27 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0002_alter_blogpostimage_blogpost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='connection_platform',
            new_name='social_platform',
        ),
        migrations.RenameField(
            model_name='blogpost',
            old_name='connect_author',
            new_name='social_username',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='cover_image',
            field=models.ImageField(blank=True, upload_to='blogpost-cover-images'),
        ),
    ]
