# Generated by Django 5.0.6 on 2024-07-01 22:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0003_rename_connection_platform_blogpost_social_platform_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpostimage',
            name='blogpost',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='repo.blogpost'),
        ),
    ]
