# Generated by Django 5.0.6 on 2024-07-01 23:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0004_alter_blogpostimage_blogpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpostimage',
            name='blogpost',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_images', to='repo.blogpost'),
        ),
    ]
