# Generated by Django 5.0.6 on 2024-05-25 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0004_alter_blogpost_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpostimage',
            name='blogpost',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='repo.blogpost'),
        ),
    ]
